project:
  type: website

website:
  title: "website_learn"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual


title: "Finley Malloc"
about:
  id: hero-heading
  template: jolla
  image: final_solid_grey.png
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com


